export const GET_DOGS = "GET_DOGS";
export const GET_BY_NAME = "GET_BY_NAME";
export const GET_TEMPERAMENT = "GET_TEMPERAMENT";
export const FILTER_BY_TEMPER = "FILTER_BY_TEMPER";
export const FILTER_BY_CREATED= "FILTER_BY_CREATED";
export const ORDER = "ORDER";
export const POST = "POST";
export const GET_DOGS_DETAIL = "GET_DOGS_DETAIL";
export const CLEAR_PAGE = "CLEAR_PAGE";